global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'contas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8888']


  - job_name: 'analise'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9999']